; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31329.0 

	TITLE	D:\ÄÚµù\Raven\Buckland_Chapter7 to 10_Raven\Debug\Goal_SayPhrase.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
